### ISSUE TITLE
Agregar y llenar columnas TIPO_ARCHIVO y CANTIDAD_ARCHIVOS a dataset concentrado parquet

### ISSUE THREAD

**Issue by xuxoramos** [sociedat/score-respuesta-inai#14]
- [x] Agregar columna TIPO_ARCHIVO al archivo parquet
- [x] Hacerle CURL o WGET u otro mecanismo en Python al URL en la columna ARCHIVO de los datasets originales
- [x] Obtener el MIME type del archivo
- [x] Escribir el tipo de archivo en la columna TIPO_ARCHIVO
- [x] Si el archivo es ZIP, abrirlo y contar archivos que contiene
- [x] Escribir este conteo de archivos en nueva columna CANTIDAD_ARCHIVOS_EN_ZIP

**Comment by dvilla88** [comment]
Hola Jesus, 
Te confirmo que esta issue ya quedo solventado. En la S3 en la carpeta parquet se encuentra un archivo parquet consolidado con información del 2012 al 2019 con las 2 columnas nuevas (tipo_archivo_respuesta y cantidad_archivos_respuesta).

**Comment by xuxoramos** [comment]
![image](https://user-images.githubusercontent.com/1316464/85080993-57859280-b190-11ea-9f52-6e63c8da9aa1.png)
https://inai-summerofdata.s3-us-west-2.amazonaws.com/parquet/inai.parquet

**Comment by rafaelortegar** [comment]
![Captura de pantalla de 2020-06-18 18-21-19](https://user-images.githubusercontent.com/51694410/85081100-a6cbc300-b190-11ea-9347-75993ab9f88e.png)

**Comment by xuxoramos** [comment]
Validado el issue. Se cierra.
