### ISSUE TITLE
Crear archivo parquet concentrado 2012-2019

### ISSUE THREAD

**Issue by xuxoramos** [sociedat/score-respuesta-inai#16]
Fusionar archivos XLS desde 2012 a 2019 (A y B) en un solo archivo en formato parquet.

Opcionalmente, las columnas definidas en #14 deben quedar ANTES de conformar este dataset concentrado agregándolos en los XLS, ó bien, DESPUÉS de que haya quedado conformado, directo en el parquet (desconozco si un archivo parquet se puede alterar, escribir, modificar, etc).

**Comment by dvilla88** [comment]
Hola Jesus,
Te confirmo que esta issue ya quedo solventado. En la S3 en la carpeta parquet se encuentra un archivo parquet consolidado con información del 2012 al 2019 con las 2 columnas nuevas (tipo_archivo_respuesta y cantidad_archivos_respuesta).

**Comment by rafaelortegar** [comment]
El archivo parquet se encuentra en la liga `s3://inai-summerofdata/parquet/inai.parquet`

y las columnas han sido añadidas correctamente, se adjunta evidencia:

![Captura de pantalla de 2020-06-18 18-21-19](https://user-images.githubusercontent.com/51694410/85083934-e696a880-b198-11ea-98f5-a59d5e4cd706.png)

**Comment by xuxoramos** [comment]
Se cierra el issue.
