### ISSUE TITLE
Descarga de adjuntos en PDF

### ISSUE THREAD

**Issue by xuxoramos** [sociedat/score-respuesta-inai#17]
Del archivo parquet concentrado y creado en #16 
- Seleccionar registros que tengan adjuntos PDF (ver issue #15)
- Iterarlos
- Extraer valor de columna ARCHIVO
- Ejecutar comando CURL o WGET o su equivalente en algún lenguaje de prog en el URL obtenido de la columna ARCHIVO
- Almacenar adjunto descargado de forma que se pueda relacionar con el folio (ID) de la solicitud de información

**Comment by dvilla88** [comment]
Hola Jesus,

Te confirmo que este issue ya quedó solventado. Los archivos adjuntos en PDF se encuentran en la S3 en la carpeta raw/respuestas_adjuntos con el formato segurido "folio".pdf

**Comment by xuxoramos** [comment]
Se confirma la carga de los ~550K PDFs.
![image](https://user-images.githubusercontent.com/1316464/85084062-4c833000-b199-11ea-89f2-1d45086f2d02.png)
