### ISSUE TITLE
Extraer texto de adjuntos PDF descargados

### ISSUE THREAD

**Issue by xuxoramos** [sociedat/score-respuesta-inai#18]
De los PDF descargados en #17:
- Ejecutar AWS Textract
- Buscar términos de rechazo o información clasificada
- Si se encuentran palabras que sugieran info clasificada, marcar folio de registro en parquet (creado en #16) como "negado" en columna RESPUESTA_ADJUNTO

**Comment by dvilla88** [comment]
Hola Xuxo, 

Confirmo que el primer punto (Ejecutar AWS Textract) ya quedo solventado, el archivo inai.parquet ya incluye la columna "texto_respuesta_adjunto" la cual contiene el texto extraído de los archivos pdf.

Se adjunta imagen con evidencia.

<img width="501" alt="Captura de Pantalla 2020-07-01 a la(s) 10 47 56" src="https://user-images.githubusercontent.com/51724809/86264808-951eee00-bb88-11ea-924a-8f17dd22b38f.png">

Nota: Los dos puntos pendientes hacen referencia al issue #22 para los cuales se necesitan las reglas de negocio del issue #25

**Comment by xuxoramos** [comment]
Se cierra el issue dado que el feature está completo en el archivo. Se completaron ~50% de archivos PDF extraídos. El restante 50% se atenderá en conjunción con #21 .
