### ISSUE TITLE
Crear feature/columna "respuesta_real" en inai.parquet

### ISSUE THREAD

**Issue by xuxoramos** [sociedat/score-respuesta-inai#22]
En el arhcivo `inai.parquet` creado en #16 , agregar columna "respuesta_real", que se llenará de acuerdo a la siguiente lista de reglas, que es enunciativa, mas no exhaustiva:

1. `if  file.extension() ='ZIP' & file.zip.content() >= 5 then { solicitud.respuesta_real = soliciutd.respuesta }`
2. si el texto extraído de un PDF adjunto (contenido o no en un ZIP, cuando ésto se de) contiene alguna de las keywords definidas en el [diccionario entregado por SocialTIC](https://docs.google.com/document/d/1L6PqrXLgdes9SyW6MC640AWw8njU2KyRob8hCRTFKkM/edit), entonces `solicitud.respuesta_real = "rechazada en adjunto"` - _se deberá tener una sesión con @jmcasanueva para clarificar contenido de este diccionario_

Se agregarán más reglas conforme vaya avanzando el proyecto.

**Comment by dvilla88** [comment]
Hola Xuxo, 

Se creó la columna respuestareal con las reglas de negocio del issue #25. El archivo inai.parquet se encuentra actualizado en la S3 en la carpeta mlpreproc.

Imagen con evidencia.
<img width="566" alt="Captura de Pantalla 2020-07-07 a la(s) 17 03 48" src="https://user-images.githubusercontent.com/51724809/86853650-26540000-c074-11ea-9b62-f704645c69a5.png">

**Comment by xuxoramos** [comment]
Se cierra el issue.
