### ISSUE TITLE
Complementar textos extraídos con archivos con extensión ".PDF" en mayúscula

### ISSUE THREAD

**Issue by xuxoramos** [sociedat/score-respuesta-inai#23]
Los adjuntos a los que se les debe extraer el texto son los archivos PDF.

Sin embargo, al momento de descargar del URL el adjunto, aparecen archivos con extensiones `.PDF` y `.pdf`. Aunque estos últimos son la mayoría, los primeros deben incluirse en la extracción.

Dado que la extracción de los archivos `.pdf` ya se inició y es un proceso bastante tardado, esta extracción de archivos `.PDF` comenzará una vez terminado el primero.

**Comment by dvilla88** [comment]
Hola Xuxo,

Este issue queda solventado, se ha hecho la extracción de texto de los archivos con extension .PDF y se ha actualizado la columna "texto_respuesta_adjunto" en el archivo inai.parquet

Se incluye evidencia.

<img width="487" alt="Captura de Pantalla 2020-07-02 a la(s) 0 26 49" src="https://user-images.githubusercontent.com/51724809/86320791-3e073080-bbfd-11ea-84d4-a8605608880b.png">

**Comment by xuxoramos** [comment]
Se cierra debido a que el feature ya quedó agregado a la matriz de diseño.
