### ISSUE TITLE
Completar limpieza de textos de solicitud con diccionario de SocialTIC

### ISSUE THREAD

**Issue by xuxoramos** [sociedat/score-respuesta-inai#30]
Completar la limpieza de textos abiertos de solicitud de información con diccionario creado por SocialTIC.

Se adjunta diccionario:
[stopwordsadicionalesinai.txt](https://github.com/sociedat/score-respuesta-inai/files/4867084/stopwordsadicionalesinai.txt)

**Comment by dvilla88** [comment]
Hola Xuxo, 

Confirmo que este issue ha sido solventado, se eliminaron stopwords (diccionario compratido por SocialTIC) de la columna "descripcionsolicitud". El archivo parquet que ya tiene este cambio se encuentra en la S3 en la carpeta mlpreproc con el nombre inai.parquet

Imagen con evidencia.
<img width="301" alt="Captura de Pantalla 2020-07-07 a la(s) 12 10 58" src="https://user-images.githubusercontent.com/51724809/86824123-f5aba080-c04a-11ea-9d6d-298bbb2eede2.png">

**Comment by xuxoramos** [comment]
Se cierra este issue
