### ISSUE TITLE
Complementar EDA: Distinct de dominios en registros de columna ARCHIVO

### ISSUE THREAD

**Issue by xuxoramos** [sociedat/score-respuesta-inai#32]
Pregunta que se desea responder: ¿a dónde apuntan las ligas a descarga de adjunto?

Se tiene por intuición que la mayoría son de INFOMEX. El EDA dará más detalle.

**Comment by rafaelortegar** [comment]
Todos los archivos se encuentran en una liga de infomex.org.mx, por lo que no tendría sentido hacer un análisis adicional al que se hizo con url's

**Comment by xuxoramos** [comment]
Se cierra el issue. Es importante destacar que infomex es la plataforma antigua de transparencia, por lo que cae como responsabilidad del INAI el eventualmente migrar los URLs.
