### ISSUE TITLE
Limpieza de columna DEPENDENCIA

### ISSUE THREAD

**Issue by xuxoramos** [sociedat/score-respuesta-inai#36]
Continuar la limpieza de columna `DEPENDENCIA` y generar columna `DEPENDENCIA_CLEAN` para tener una menor granularidad y ayudar a la clasificación.

**Comment by rafaelortegar** [comment]
para versión 2 subiré la documentación de la función y comentaré las agrupaciones realizadas

**Comment by xuxoramos** [comment]
Se cierra con PR #39
