### ISSUE TITLE
Limpieza de datos

### ISSUE THREAD

**Issue by jarotter** [sociedat/score-respuesta-inai#5]
- [x] Revisar por qué todos los exceles tienen 64,999 filas (se pierden datos, nada pasa de junio)

**Comment by dvilla88** [comment]
Hola,

Revisando la información raw de los archivos xls de los años 2012 - 2019, encontramos que la información viene distribuida en varias hojas para cada año. Por ejemplo, el archivo Solicitudes2012.xls contiene 3 hojas, la hoja 1 corresponde al primer semestre (Enero-Junio) que tiene un total de 64,999 filas.
Posiblemente, al importar al información para trabajarla en python, solo te trajiste la información de la primera hoja para cada año. (Nos paso lo mismo, cachamos esto en al fase de validaciones)

Saludos!

**Comment by xuxoramos** [comment]
Confirmamos la información. Hay diferentes hojas en el workbook de excel para diferentes semestres.
Ya se tiene el concentrado final.
